### ISSUE TITLE
How can this be used properly with gatsby?

### ISSUE THREAD

**Issue by realvictorprm** [spicydonuts/gatsby-plugin-purescript#3]
Hi,

I tried to figure out how to get this plugin working with Gatsby and some purescript code and didn't manage to get anything from purescript into gatsby so far :( Would be great to have some example code showing how to describe a page in purescript which is accepted by gatsby :)

**Comment by realvictorprm** [comment]
Just like I expected. As soon as I write an issue it won't take long till I finally figure it out myself.

Turns out that there are 2 things which are easy but important for purescript to work well with gatsby.
1. Use the correct exported name for a component within a js file in gatsby if you're using purescript for a component :smile: 
2. Gatsby wants the React component for a page to be "default exported". Solution to that is to use `default` as alias for the component you want to export in your purescript module:
```purescript
module Component(default) where
yourComponent = ....
default = yourComponent
```

**Comment by maddie927** [comment]
Yep, this just compiles the file to JS, normal Gatsby rules apply after that

**Comment by realvictorprm** [comment]
Well now I'm fighting the issue that stuff like `var gatsby = require("gatsby")` for usage in a FFI isn't working. Any usage within the JS file results in `gatsby is undefined` :(

**Comment by maddie927** [comment]
That seems unusual. Do you have the code posted anywhere?
